org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
org.gradle.configureondemand=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neoforge_version=21.1.233
neoforge_version_range=[21.1.233,)
mapping_version=2024.11.17
loader_version_range=[4,)

mod_id=openlights
mod_name=OpenLights
mod_group_id=pcl.openlights
mod_version=0.2.0
mod_license=All Rights Reserved
mod_authors=Michiyo and contributors
mod_description=OpenComputers addon that adds a programmable color-changing light.

opencomputers_version=1.9.4-2
opencomputers_version_range=[1.9.4,)
scala_loader_version=3.3.3-build-15
veil_version=4.4.1
